version: '3.8'
services:
  server:
    container_name: codeshare-app
    image: springboot
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
  postgresdb:
    container_name: postgresql
    image: postgres:14.0-bullseye
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - /pgdata:/var/lib/postgresql/data
