version: '3.8'
services:
  server:
    container_name: outside_issues
    image: beimage
    build: .
    ports:
      - "8080:8080"
    privileged: true
    devices:
      - "/dev/ttyS4:/dev/ttyS4"
    depends_on:
      - postgresdb
  postgresdb:
    container_name: postgresql
    image: postgres:15.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
#    volumes:
#      - /pgdata:/var/lib/postgresql/data
