package com.license.outside_issues.enums;

public enum IssueType {
    ROAD, LIGHTNING, GREEN_SPACES, PUBLIC_DOMAIN,
    PUBLIC_DISORDER, INSTITUTION_STAFF, PUBLIC_TRANSPORT, BUILDINGS,
    TRAFFIC_ROAD_SIGNS, ANIMALS
}
