#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#jwt.expirationTime=3600000
#jwt.secretKey=mySecret

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/outside_issues
    username: postgres
    password: postgres
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: codeshareinternship@gmail.com
    password: wvwikpslldhvrctc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  output:
    ansi:
      enabled: always
jwt:
  expirationTime: 28800000
  secretKey: mySecret
logging:
  level:
    org:
      springframework:
        security: DEBUG
base_url:
  issue: "http://localhost:3000/issues/"

#rabbitmq:
#  host: localhost
#  virtualhost: /
#  port: 15672
#  username: guest
#  password: guest
#  exchange: rabbitmq.exchange
#  queue: rabbitmq.queue
#  routingkey: rabbitmq.routingkey
#  reply:
#    timeout: 60000
#  concurrent:
#    consumers: 1
#  max:
#    concurrent:
#      consumers: 1
