spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
  mail:
    host: smtp.gmail.com
    port: 587
    username: codeshareinternship@gmail.com
    password: wvwikpslldhvrctc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  output:
    ansi:
      enabled: always
jwt:
  expirationTime: 28800000
  secretKey: mySecret
logging:
  level:
    org:
      springframework:
        security: DEBUG
base_url:
  issue: "http://localhost:3000/issues/"